---
title: "Figure S4"
author: "Lieke Vlaar"
date: "01/10/2021"
output: html_document
---
Initiate the necessary libraries:

```{r, message = FALSE, warning = FALSE}
library(ggpmisc)
library(extrafont)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(plotrix)
```

Load the necessary functions:

```{r, message = FALSE, warning = FALSE}
source("scripts/hatch_calc.R")
source("scripts/hatch_summ.R")
source("scripts/plot_grid_s4.R")
```




# DA


Concentrations of DA plot

## solA + DA plot

There will be 3 plots of DA. This is number one

```{r DA, fig.width = 3, fig.height = 4, message = FALSE, warning = FALSE}
#supplemental figure ke_solA

DA_c_solA <- hatch_calc(input = "input/DA_solA.csv")
DA_s_solA <- hatch_summ(input = "input/DA_solA.csv")
DA1_c <- DA_c_solA[DA_c_solA$treatment %in% c("d4da_100nM",
                                              "d4da_10uM",
                                              "DA0.01uM",
                                              "DA0.1uM",
                                              "DA1uM",
                                              "DA10uM"),] 
DA1_s <- DA_s_solA[DA_s_solA$treatment %in% c("d4da_100nM",
                                              "d4da_10uM",
                                              "DA0.01uM",
                                              "DA0.1uM",
                                              "DA1uM",
                                              "DA10uM"),]
DA1_s$treatment <- factor(DA1_s$treatment, levels = c("DA0.01uM",
                                                      "DA0.1uM",
                                                      "DA1uM",
                                                      "DA10uM",
                                                      "d4da_100nM",
                                                      "d4da_10uM"), ordered = TRUE)
DA1_s <- DA1_s[order(DA1_s$treatment),]
DA1_c$treatment <- factor(DA1_c$treatment, levels = c("DA0.01uM",
                                                      "DA0.1uM",
                                                      "DA1uM",
                                                      "DA10uM",
                                                      "d4da_100nM",
                                                      "d4da_10uM"), ordered = TRUE)
DA1_c <- DA1_c[order(DA1_c$treatment),]
S4A <- plotgrid3(DA1_c, DA1_s)
S4A <- S4A + scale_x_discrete(labels = c(expression(Delta*"7-DA 1\U03BCM"),
                                             expression(Delta*"7-DA 10\U03BCM"),
                                             expression(Delta*"7-DA 0.1\U03BCM"),
                                             expression(Delta*"7-DA 10\U03BCM"),
                                             expression(Delta*"4-DA 0.1\U03BCM"),
                                             expression(Delta*"4-DA 10\U03BCM")
                                             ))

S4A
```

Number 2: (B)

```{r solADA, fig.height = 6, fig.width = 2.1}
DA1c <- hatch_calc(input = "input/DA_figs4.1.csv")
DA1s <- hatch_summ5(input = "input/DA_figs4.1.csv")
DA1c$treatment <- factor(DA1c$treatment, levels = c("TRD_hsolA_dafadine_0uM_DAno",
                                                    "TRD_hsolA_dafadine_50uM_DAno",
                                                    "TRD_hsolA_dafadine_50uM_DA0.5uM",
                                                    "TRD_hsolA_dafadine_0uM_DA0.5uM"), ordered = TRUE)
DA1c <- DA1c[order(DA1c$treatment),]
DA1s$treatment <- factor(DA1s$treatment, levels = c("TRD_hsolA_dafadine_0uM_DAno",
                                                    "TRD_hsolA_dafadine_50uM_DAno",
                                                    "TRD_hsolA_dafadine_50uM_DA0.5uM",
                                                    "TRD_hsolA_dafadine_0uM_DA0.5uM"), ordered = TRUE)
DA1s <- DA1s[order(DA1s$treatment),]
S4B <- plotgrid2(c = DA1c, s = DA1s) + scale_x_discrete(labels = c("TRD_hsolA",
                                                                   "TRD_hsolA + dafadine 50\U03BCM",
                                                                   expression("TRD_hsolA + dafadine 50\U03BCM +"*Delta*"7-DA 0.5\U03BCM"),
                                                                   expression("TRD_hsolA +"*Delta*"7-DA 0.5\U03BCM")))
S4B
```

This will be the 3rd:

```{r, fig.height = 5, fig.width = 4.5}
DA2c <- hatch_calc(input = "input/DA_figs4.2.csv")
DA2s <- hatch_summ5(input = "input/DA_figs4.2.csv")
DA2c$treatment <- factor(DA2c$treatment, levels = c("solA_0.5nM__DAno",
                                                    "solA_0.5nM__DA0.5uM",
                                                    "solA_1.0nM__DAno",
                                                    "solA_1.0nM__DA0.5uM",
                                                    "solA_2.0nM__DAno",
                                                    "solA_2.0nM__DA0.5uM",
                                                    "solA_5.0nM__DAno",
                                                    "solA_5.0nM__DA0.5uM",
                                                    "solA_10nM__DAno",
                                                    "solA_10nM__DA0.5uM",
                                                    "solA_5.0nM_dafadine_DAno",
                                                    "solA_5.0nM_dafadine_DA1.0uM"), ordered = TRUE)
DA2c <- DA2c[order(DA2c$treatment),]
DA2s$treatment <- factor(DA2s$treatment, levels = c("solA_0.5nM__DAno",
                                                    "solA_0.5nM__DA0.5uM",
                                                    "solA_1.0nM__DAno",
                                                    "solA_1.0nM__DA0.5uM",
                                                    "solA_2.0nM__DAno",
                                                    "solA_2.0nM__DA0.5uM",
                                                    "solA_5.0nM__DAno",
                                                    "solA_5.0nM__DA0.5uM",
                                                    "solA_10nM__DAno",
                                                    "solA_10nM__DA0.5uM",
                                                    "solA_5.0nM_dafadine_DAno",
                                                    "solA_5.0nM_dafadine_DA1.0uM"), ordered = TRUE)
DA2s <- DA2s[order(DA2s$treatment),]
S4C<- plotgrid3(c = DA2c, s = DA2s) + 
  scale_x_discrete(labels = c("solA 0.5nM",
                              expression("solA 0.5nM +"*Delta*"7-DA 0.5\U03BCM"),
                              "solA 1.0nM",
                              expression("solA 1.0nM +"*Delta*"7-DA 0.5\U03BCM"),
                              "solA 2.0nM",
                              expression("solA 2.0nM +"*Delta*"7-DA 0.5\U03BCM"),
                              "solA 5.0nM",
                              expression("solA 5.0nM +"*Delta*"7-DA 0.5\U03BCM"),
                              "solA 10nM",
                              expression("solA 10nM +"*Delta*"7-DA 0.5\U03BCM"),
                              "solA 5.0nM + dafadine 50\U03BCM",
                              expression("solA 5.0nM + dafadine 50\U03BCM +"*Delta*"7-DA 1\U03BCM")
                              ))
S4C
```